scrape_configs:
  - job_name: cadvicsor
    scrape_interval: 5s
    static_configs:
      - targets: 
        - cadvisor:8080
  - job_name: node
    scrape_interval: 5s
    static_configs:
      - targets: 
        - node-exporter:9100